<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7d604dd19d23f653b08e385ab7b1b609
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DPM\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DPM\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7d604dd19d23f653b08e385ab7b1b609::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7d604dd19d23f653b08e385ab7b1b609::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
